"""add_linked_content_columns

Revision ID: d232d838dd4b
Revises: fb478a0a4673
Create Date: 2026-07-07 10:56:06.894613

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d232d838dd4b"
down_revision: str | Sequence[str] | None = "fb478a0a4673"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("articles", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("linked_content_markdown", sa.String(), nullable=True)
        )
        batch_op.add_column(
            sa.Column("linked_fetched_at", sa.DateTime(), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("articles", schema=None) as batch_op:
        batch_op.drop_column("linked_fetched_at")
        batch_op.drop_column("linked_content_markdown")

    # ### end Alembic commands ###
