"""v2 baseline

Revision ID: v2baseline
Revises:
Create Date: 2026-07-04 10:48:12.613981

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "v2baseline"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("display_name", sa.String(), nullable=False),
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("weight", sa.String(), nullable=False),
        sa.Column("needs_triage", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "weight IN ('block', 'reduce', 'normal', 'boost', 'max')",
            name="ck_categories_weight",
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["categories.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("categories", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_categories_display_name"), ["display_name"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_categories_slug"), ["slug"], unique=True)

    op.create_table(
        "feed_folders",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("display_order", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("feed_folders", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_feed_folders_name"), ["name"], unique=True)

    op.create_table(
        "user_preferences",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("interests", sa.String(), nullable=False),
        sa.Column("anti_interests", sa.String(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("feed_refresh_interval", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "category_aliases",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("alias_slug", sa.String(), nullable=False),
        sa.Column("target_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["target_id"], ["categories.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("category_aliases", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_category_aliases_alias_slug"), ["alias_slug"], unique=True
        )

    op.create_table(
        "feeds",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("url", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("display_order", sa.Integer(), nullable=False),
        sa.Column("last_fetched_at", sa.DateTime(), nullable=True),
        sa.Column("is_aggregator", sa.Boolean(), nullable=False),
        sa.Column("folder_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["folder_id"], ["feed_folders.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("feeds", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_feeds_folder_id"), ["folder_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_feeds_url"), ["url"], unique=True)

    op.create_table(
        "articles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("feed_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("url", sa.String(), nullable=False),
        sa.Column("author", sa.String(), nullable=True),
        sa.Column("published_at", sa.DateTime(), nullable=True),
        sa.Column("summary", sa.String(), nullable=True),
        sa.Column("content", sa.String(), nullable=True),
        sa.Column("content_markdown", sa.String(), nullable=True),
        sa.Column("is_read", sa.Boolean(), nullable=False),
        sa.Column("rating", sa.Integer(), nullable=True),
        sa.Column("interest_score", sa.Integer(), nullable=True),
        sa.Column("quality_score", sa.Integer(), nullable=True),
        sa.Column("composite_score", sa.Float(), nullable=True),
        sa.Column("score_reasoning", sa.String(), nullable=True),
        sa.Column("scoring_state", sa.String(), nullable=False),
        sa.Column("scored_at", sa.DateTime(), nullable=True),
        sa.Column("scoring_priority", sa.Integer(), nullable=False),
        sa.Column("rescore_mode", sa.String(), nullable=True),
        sa.Column("categorization_state", sa.String(), nullable=False),
        sa.Column("categorization_attempts", sa.Integer(), nullable=False),
        sa.Column("scoring_attempts", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "categorization_state IN ('uncategorized', 'queued', 'categorizing', 'categorized', 'failed')",
            name="ck_articles_categorization_state",
        ),
        sa.CheckConstraint(
            "rescore_mode IS NULL OR rescore_mode IN ('score_only')",
            name="ck_articles_rescore_mode",
        ),
        sa.CheckConstraint(
            "scoring_state IN ('unscored', 'queued', 'scoring', 'scored', 'blocked', 'failed')",
            name="ck_articles_scoring_state",
        ),
        sa.CheckConstraint(
            "rating IS NULL OR rating IN (-1, 1)", name="ck_articles_rating"
        ),
        sa.ForeignKeyConstraint(["feed_id"], ["feeds.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("articles", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_articles_categorization_state"),
            ["categorization_state"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_articles_composite_score"), ["composite_score"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_articles_feed_id"), ["feed_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_articles_published_at"), ["published_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_articles_scoring_state"), ["scoring_state"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_articles_url"), ["url"], unique=True)

    op.create_table(
        "article_category_link",
        sa.Column("article_id", sa.Integer(), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["article_id"], ["articles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["category_id"], ["categories.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("article_id", "category_id"),
    )
    op.create_table(
        "feedback_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("article_id", sa.Integer(), nullable=False),
        sa.Column("event_type", sa.String(), nullable=False),
        sa.Column("value", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "event_type IN ('opened', 'marked_read', 'rated', 'rescued')",
            name="ck_feedback_events_event_type",
        ),
        sa.CheckConstraint(
            "value IS NULL OR value IN (-1, 1)", name="ck_feedback_events_value"
        ),
        sa.ForeignKeyConstraint(["article_id"], ["articles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("feedback_events", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_feedback_events_article_id"), ["article_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("feedback_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_feedback_events_article_id"))

    op.drop_table("feedback_events")
    op.drop_table("article_category_link")
    with op.batch_alter_table("articles", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_articles_url"))
        batch_op.drop_index(batch_op.f("ix_articles_scoring_state"))
        batch_op.drop_index(batch_op.f("ix_articles_published_at"))
        batch_op.drop_index(batch_op.f("ix_articles_feed_id"))
        batch_op.drop_index(batch_op.f("ix_articles_composite_score"))
        batch_op.drop_index(batch_op.f("ix_articles_categorization_state"))

    op.drop_table("articles")
    with op.batch_alter_table("feeds", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_feeds_url"))
        batch_op.drop_index(batch_op.f("ix_feeds_folder_id"))

    op.drop_table("feeds")
    with op.batch_alter_table("category_aliases", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_category_aliases_alias_slug"))

    op.drop_table("category_aliases")
    op.drop_table("user_preferences")
    with op.batch_alter_table("feed_folders", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_feed_folders_name"))

    op.drop_table("feed_folders")
    with op.batch_alter_table("categories", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_categories_slug"))
        batch_op.drop_index(batch_op.f("ix_categories_display_name"))

    op.drop_table("categories")
    # ### end Alembic commands ###
